---
- name: Enable intranet services
  hosts: rhel9-1
  become: true
  gather_facts: false
  tasks:
    - name: Install software
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: present

    - name: Deploy index.html
      ansible.builtin.copy:
        content: |
          Welcome to the example.com intranet!
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow firewall access
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Start and enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

- name: Check file permissions for webserver
  hosts: rhel9-1
  become: true
  gather_facts: false
  tasks:
    - name: Obtain the ACLs for /webserver_data directory
      ansible.posix.acl:
        path: /var/www/html/
      register: acl_info

    - name: Print the ACLs obtained for /webserver_data directory
      ansible.builtin.debug:
        var: acl_info['acl']

- name: Test intranet web server
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Test access to intranet web server
      ansible.builtin.uri:
        url: http://192.168.192.128
        return_content: true
        status_code: 200
